-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : lun. 27 jan. 2025 à 12:40
-- Version du serveur : 8.3.0
-- Version de PHP : 8.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `skydiary`
--

-- --------------------------------------------------------

--
-- Structure de la table `post`
--

DROP TABLE IF EXISTS `post`;
CREATE TABLE IF NOT EXISTS `post` (
  `id_post` int NOT NULL AUTO_INCREMENT,
  `date_published` date NOT NULL,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `under_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `intro` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `contain` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `pic` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `id_user` int NOT NULL,
  PRIMARY KEY (`id_post`),
  KEY `USER` (`id_user`)
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `post`
--

INSERT INTO `post` (`id_post`, `date_published`, `title`, `under_title`, `intro`, `contain`, `pic`, `id_user`) VALUES
(7, '2024-11-29', 'The Art of Black-and-White Photography', 'Why Black-and-White Photography?', 'Black-and-white photography is a timeless art form that transcends trends and technology. By stripping away color, this medium emphasizes composition, texture, and emotion, creating images that are both powerful and evocative.', 'Timeless Aesthetic:\r\nBlack-and-white images possess a classic and enduring quality that color photographs often lack.\r\nFocus on Composition:\r\nWithout the distraction of color, elements such as shape, contrast, and light take center stage.\r\nEnhanced Emotional Impact:\r\nThe absence of color allows viewers to focus on the subject’s emotions and the story being told.\r\n\r\nConclusion\r\n\r\nBlack-and-white photography challenges photographers to think beyond color and focus on the essence of their subjects. By mastering this art form, you can create images that are not only visually compelling but also deeply meaningful. Pick up your camera, embrace the shades of gray, and start your journey into the world of black-and-white photography today.', 'img\\article-image.png', 11),
(8, '2024-11-29', 'The Importance of Editing: Polishing Your Work as a Personal Author', 'Why Black-and-White Photography?', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pharetra quis lacus ullamcorper malesuada. Curabitur volutpat ligula vel convallis vulputate. Curabitur aliquam venenatis ornare. Maecenas auctor magna nec elit convallis, sit amet auctor orci pretium. Donec ac leo ac ipsum rhoncus sodales. Nam varius hendrerit ipsum nec elementum. Donec bibendum lectus sodales dignissim auctor. Sed nec tempus orci.\r\n\r\n', 'Vestibulum at nunc in ipsum bibendum pharetra eu non metus. Duis a nulla pharetra ligula posuere euismod. Nullam suscipit metus nec diam malesuada blandit. In lacus ligula, scelerisque at suscipit at, porttitor eget augue. Donec ac congue mi. Fusce et ligula gravida nibh porta fringilla ut id libero. Proin aliquet ut justo eget venenatis. Praesent id ex suscipit, luctus ipsum at, viverra velit. Donec porttitor risus eu dapibus blandit. Pellentesque pellentesque sit amet justo id tempus. Sed id lacus augue. Aenean quis sodales nisl. Integer velit nibh, posuere sit amet sem eget, rhoncus ultrices magna. Fusce finibus fermentum condimentum.\r\n\r\nMauris in maximus mi, quis mattis tellus. Mauris augue mauris, pharetra eget malesuada non, faucibus sit amet urna. Aliquam ut iaculis velit. Maecenas tincidunt augue sit amet dictum sagittis. Etiam maximus diam aliquet ex interdum, id semper ipsum lobortis. Sed non euismod massa, vitae venenatis tortor. Ut bibendum efficitur ornare. Phasellus sed tristique velit. In porttitor purus non lorem facilisis bibendum. Aenean eleifend eros risus, cursus rutrum quam ornare at. Phasellus mattis nunc a accumsan fermentum. Duis orci sem, viverra vitae eros tincidunt, dignissim convallis augue. Praesent efficitur elit libero, ut aliquam turpis ultrices eu. Ut metus dolor, vulputate sed ipsum sed, rhoncus consequat nisi. Morbi felis odio, varius sit amet dictum quis, lobortis non purus.', 'img\\importance_editing.png', 11),
(9, '2024-11-29', 'Crafting a Personal Brand as an Author: Tips for Success', 'Why Black-and-White Photography?', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pharetra quis lacus ullamcorper malesuada. Curabitur volutpat ligula vel convallis vulputate. Curabitur aliquam venenatis ornare. Maecenas auctor magna nec elit convallis, sit amet auctor orci pretium. Donec ac leo ac ipsum rhoncus sodales. Nam varius hendrerit ipsum nec elementum. Donec bibendum lectus sodales dignissim auctor. Sed nec tempus orci.\r\n\r\n', 'Vestibulum at nunc in ipsum bibendum pharetra eu non metus. Duis a nulla pharetra ligula posuere euismod. Nullam suscipit metus nec diam malesuada blandit. In lacus ligula, scelerisque at suscipit at, porttitor eget augue. Donec ac congue mi. Fusce et ligula gravida nibh porta fringilla ut id libero. Proin aliquet ut justo eget venenatis. Praesent id ex suscipit, luctus ipsum at, viverra velit. Donec porttitor risus eu dapibus blandit. Pellentesque pellentesque sit amet justo id tempus. Sed id lacus augue. Aenean quis sodales nisl. Integer velit nibh, posuere sit amet sem eget, rhoncus ultrices magna. Fusce finibus fermentum condimentum.\r\n\r\nMauris in maximus mi, quis mattis tellus. Mauris augue mauris, pharetra eget malesuada non, faucibus sit amet urna. Aliquam ut iaculis velit. Maecenas tincidunt augue sit amet dictum sagittis. Etiam maximus diam aliquet ex interdum, id semper ipsum lobortis. Sed non euismod massa, vitae venenatis tortor. Ut bibendum efficitur ornare. Phasellus sed tristique velit. In porttitor purus non lorem facilisis bibendum. Aenean eleifend eros risus, cursus rutrum quam ornare at. Phasellus mattis nunc a accumsan fermentum. Duis orci sem, viverra vitae eros tincidunt, dignissim convallis augue. Praesent efficitur elit libero, ut aliquam turpis ultrices eu. Ut metus dolor, vulputate sed ipsum sed, rhoncus consequat nisi. Morbi felis odio, varius sit amet dictum quis, lobortis non purus.', 'img\\crafting.png', 11),
(10, '2024-11-29', 'The Art of Writing: How Personal Authors Find Inspiration Everywhere', 'Why Black-and-White Photography?', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pharetra quis lacus ullamcorper malesuada. Curabitur volutpat ligula vel convallis vulputate. Curabitur aliquam venenatis ornare. Maecenas auctor magna nec elit convallis, sit amet auctor orci pretium. Donec ac leo ac ipsum rhoncus sodales. Nam varius hendrerit ipsum nec elementum. Donec bibendum lectus sodales dignissim auctor. Sed nec tempus orci.\r\n\r\n', 'Vestibulum at nunc in ipsum bibendum pharetra eu non metus. Duis a nulla pharetra ligula posuere euismod. Nullam suscipit metus nec diam malesuada blandit. In lacus ligula, scelerisque at suscipit at, porttitor eget augue. Donec ac congue mi. Fusce et ligula gravida nibh porta fringilla ut id libero. Proin aliquet ut justo eget venenatis. Praesent id ex suscipit, luctus ipsum at, viverra velit. Donec porttitor risus eu dapibus blandit. Pellentesque pellentesque sit amet justo id tempus. Sed id lacus augue. Aenean quis sodales nisl. Integer velit nibh, posuere sit amet sem eget, rhoncus ultrices magna. Fusce finibus fermentum condimentum.\r\n\r\nMauris in maximus mi, quis mattis tellus. Mauris augue mauris, pharetra eget malesuada non, faucibus sit amet urna. Aliquam ut iaculis velit. Maecenas tincidunt augue sit amet dictum sagittis. Etiam maximus diam aliquet ex interdum, id semper ipsum lobortis. Sed non euismod massa, vitae venenatis tortor. Ut bibendum efficitur ornare. Phasellus sed tristique velit. In porttitor purus non lorem facilisis bibendum. Aenean eleifend eros risus, cursus rutrum quam ornare at. Phasellus mattis nunc a accumsan fermentum. Duis orci sem, viverra vitae eros tincidunt, dignissim convallis augue. Praesent efficitur elit libero, ut aliquam turpis ultrices eu. Ut metus dolor, vulputate sed ipsum sed, rhoncus consequat nisi. Morbi felis odio, varius sit amet dictum quis, lobortis non purus.', 'img\\art_writting.png', 11),
(80, '2025-01-22', 'The Perfect oatmeal Cookies', 'A Healthy and Delicious Treat for Any Occasion', 'Who can resist a batch of warm, chewy oatmeal cookies fresh out of the oven? Packed with wholesome oats and a touch of sweetness, these cookies strike the perfect balance between indulgence and nutrition. Whether you\'re looking for a quick snack or a dessert to share, this recipe will win over your taste buds and your heart.', 'Ingredients\r\n\r\n1 cup (100g) rolled oats\r\n1 cup (125g) all-purpose flour\r\n1/2 teaspoon baking soda\r\n1/4 teaspoon salt\r\n1/2 cup (115g) unsalted butter, softened\r\n1/2 cup (100g) brown sugar, packed\r\n1/4 cup (50g) granulated sugar\r\n1 large egg\r\n1 teaspoon vanilla extract\r\n1/2 cup (75g) raisins or chocolate chips (optional)\r\nInstructions\r\n\r\nPreheat the Oven\r\nPreheat your oven to 350°F (175°C) and line a baking sheet with parchment paper.\r\n\r\nMix Dry Ingredients\r\nIn a medium bowl, whisk together the oats, flour, baking soda, and salt. Set aside.\r\n\r\nCream Butter and Sugars\r\nIn a large mixing bowl, use a hand mixer or stand mixer to beat the softened butter, brown sugar, and granulated sugar until light and fluffy.\r\n\r\nAdd Wet Ingredients\r\nBeat in the egg and vanilla extract until fully combined.\r\n\r\nCombine Wet and Dry\r\nGradually add the dry ingredients to the wet ingredients, mixing until just combined. If desired, fold in raisins or chocolate chips.\r\n\r\nScoop and Shape\r\nScoop tablespoons of dough and roll them into balls. Place them on the prepared baking sheet, leaving about 2 inches between each cookie. Flatten slightly with your hand.\r\n\r\nBake\r\nBake for 10–12 minutes, or until the edges are golden brown and the centers look slightly undercooked. They will continue to firm up as they cool.\r\n\r\nCool and Enjoy\r\nLet the cookies cool on the baking sheet for 5 minutes before transferring them to a wire rack to cool completely. Serve and enjoy!\r\n\r\nTips\r\n\r\nFor a chewier texture, chill the dough for 30 minutes before baking.\r\nAdd a pinch of cinnamon or nutmeg for extra warmth and flavor.\r\nYour oatmeal cookies are now ready to enjoy! Perfect with a cup of tea, coffee, or a glass of milk.', 'uploads\\Cookies.webp', 13),
(81, '2025-01-23', 'The Art of Finding Balance in a Busy World', 'How to Prioritize Yourself Without Sacrificing Your Goals', 'In today’s fast-paced society, finding balance can feel like an impossible task. With work deadlines, social obligations, and personal aspirations pulling us in different directions, it’s easy to lose sight of what truly matters. This post will explore practical strategies to regain control and prioritize your well-being without compromising your goals.', 'Start Your Day with Intention\r\nBegin each morning by setting clear goals for the day. A simple five-minute journaling session can help you outline what’s important and mentally prepare for the challenges ahead.\r\n\r\nLearn to Say No\r\nOne of the most powerful ways to find balance is by learning to say no. Evaluate your commitments and ask yourself: “Does this align with my priorities?” Saying no to what doesn’t serve you makes room for what truly matters.\r\n\r\nEmbrace Small Wins\r\nBalance doesn’t mean perfection. Celebrate small achievements, whether it’s completing a task, spending time with loved ones, or simply taking a break.\r\n\r\nDisconnect to Reconnect\r\nIn a world dominated by screens, stepping away from technology can be a game-changer. Dedicate specific times to unplug, reflect, and connect with the present moment.\r\n\r\nBy implementing these steps, you’ll not only find balance but also rediscover the joy in everyday life. Remember, achieving balance isn’t about doing it all; it’s about doing what matters most.\r\n\r\n', 'uploads\\art-of-finding.webp', 17),
(82, '2025-01-23', 'The Power of Small Habits for Big Changes', 'Transform Your Life One Step at a Time', 'We often think big changes require drastic actions. But the truth is, it’s the small, consistent habits we cultivate that lead to lasting transformation. This post dives into the science behind small habits and provides practical tips to implement them into your daily life.', 'Why Small Habits Matter\r\nSmall habits compound over time, creating significant results. For example, reading just one page a day can lead to finishing several books in a year. By focusing on manageable actions, you set yourself up for sustainable progress.\r\n\r\nStart with One Change\r\nPick one habit you want to build and start small. If your goal is to exercise, begin with 5 minutes a day. Starting small reduces overwhelm and builds confidence as you succeed.\r\n\r\nMake It Easy and Accessible\r\nRemove barriers to your new habit. If you want to drink more water, keep a water bottle nearby at all times. Simplifying the process increases the chances of sticking to it.\r\n\r\nCelebrate Small Wins\r\nRecognize and reward yourself for completing even the tiniest steps. This positive reinforcement strengthens the habit and keeps you motivated.\r\n\r\nConclusion:\r\nBig transformations don’t happen overnight. They are the result of small, consistent efforts over time. Start today with one small habit and watch how it shapes your future. Remember, success is built one step at a time.', 'uploads\\small-habit.webp', 14),
(86, '2025-01-24', 'I see you', 'You cannot, hide, you cannot escape my gaze, I see through your soul. I AM YOUR MASTER', 'En gros l\'article il tue smr', 'Une fois quand j\'étais petit j\'ai mangé des pâtes', './uploads/FR39lKPWYAAKvuq.jpg', 14),
(87, '2025-01-24', 'My new and first (but not last) post !', 'Mais Weshhhh !!!!!', 'This is my introduction..... it\'s done !', 'What can i say ? i really don\'t know.....Mell00w is amazing !!!!!', './uploads/banniere-pokémon.webp', 18),
(88, '2025-01-24', 'L\'ECF touche à sa fin, toujours les mêmes sont en tête, @Nefer, @Mel00w', 'Bien t\'as vu', 'Lors de l\'ECF 2 nous avons tous charbonné mais Vincent et Lucile ont carrément tout déchiré.', 'Je suis content de m\'être inscrit sur ce site pour pouvoir poster mes sentiments. \r\n\r\nje vous remercie de votre lecture. A bientôt sur vsCode les Loulous\r\n', 'uploads\\post-valentin.webp', 16),
(89, '2025-01-27', 'How to Stay Motivated While Learning Web Development', 'Practical tips and advice for aspiring developers to keep pushing forward.', 'Learning web development can feel overwhelming at times, especially with the constant evolution of tools and frameworks. Whether you\'re just starting or have been at it for a while, staying motivated is key to your success. In this post, I’ll share some tips to help you stay on track and keep your enthusiasm alive.', 'Set Clear Goals\r\nBreak down what you want to achieve into small, actionable steps. For instance, instead of \"I want to learn React,\" set a goal like \"Build a to-do app in React by the end of the month.\" This gives you a clear direction.\r\n\r\nCelebrate Small Wins\r\nEvery little accomplishment matters, whether it’s fixing a bug, completing a module, or publishing your first webpage. Reward yourself for progress—it’s a great way to stay positive.\r\n\r\nJoin a Community\r\nSurround yourself with other learners or experienced developers. Platforms like Discord, forums, or meetups can provide encouragement, answers to questions, and networking opportunities.\r\n\r\nBalance Learning and Practice\r\nInstead of endlessly watching tutorials, dedicate time to build projects. Applying what you learn helps you retain information and makes learning more enjoyable.\r\n\r\nTake Breaks\r\nBurnout is real. Step away from your screen when you’re feeling stuck or frustrated. Sometimes, a little rest can provide the clarity you need.\r\n\r\nConclusion:\r\nMotivation in web development is like a muscle—it needs regular exercise to stay strong. By setting goals, celebrating progress, engaging with the community, and maintaining balance, you can keep your learning journey exciting and fulfilling. Keep coding, and remember: progress is progress, no matter how small!', 'uploads\\DALL·E 2025-01-27 11.40.59 - A modern workspace setup with a laptop displaying a colorful code editor, a notebook with handwritten coding notes, and motivational sticky notes on t.webp', 20),
(90, '2025-01-27', 'My Day of Big Adventures!', 'Thoughts from a 1.5-year-old explorer!', 'Hello! I’m a big kid now, 1 year and 6 months old! Today was super busy—so many things happened! I’m here to tell you all about my big adventures.', 'Morning Yum-Yums\r\nI woke up and said, “Mama! Dada!” until they came to get me. Then, I had my favorite breakfast—BANANA! I love banana. It’s squishy and yummy and I can hold it ALL BY MYSELF.\r\n\r\nToy Time\r\nAfter breakfast, I played with my blocks. I made a big tower, then… BOOM! Knocked it down! So funny. I laughed, then I did it again. Blocks are the best.\r\n\r\nNap? No Thanks!\r\nMama said, “Nap time,” but I said, “Nooooo!” I’m not tired (okay, maybe a little). I ran around instead and played with my teddy. He’s my best friend.\r\n\r\nSnack Attack!\r\nCrackers and apples for snack! But guess what? I dropped my cracker, and the doggy ate it! I said, “Nooo, doggy!” but he just wagged his tail. Silly doggy.\r\n\r\nBath Splash\r\nAt bath time, I splashed and splashed until the floor got all wet. Oops! But splashing is so fun! I love bubbles too—POP, POP, POP!\r\n\r\nConclusion:\r\nNow I’m sleepy… but I had so much fun today. Tomorrow, I’m gonna build an even BIGGER tower. Goodnight, everyone!', 'uploads\\7620f6b6-868c-4e3c-a284-c5c24412344a.webp', 21);

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id_user` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `profile_picture` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id_user`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user` (`id_user`, `username`, `profile_picture`, `email`, `password`) VALUES
(11, 'Laura', './img/laura.png', 'laura.badler@gmail.com', '$2y$10$dl7RjZ6rp0.n/G6DVpi77.q.mOJf.RhEWtAC0a3B5T9fF244XE3Ba'),
(12, 'Lucile', 'uploads/lucile.png', 'lucile.chardard@gmail.com', '$2y$10$2XUctmHEm2staQ34PIJBkeBLaFYgGwVTR1Mzc0KWmbfsVJG6/u7NG'),
(13, 'Mel00w', 'uploads/lucile.png', 'mel00w.tv@gmail.com', '$2y$10$VXgklDPzxiClSVwZcGwCtuD2QRxo.4HVqWa.e6UYefmiOpNdZbiqG'),
(14, 'samy', './img/6790ff44ea609-samy.png', 'mechiche.samysm@gmail.com', '$2y$10$GJkLPGqsZb6YIe.e8J1F/e/l2TUIRfX.M9EapyB4AnWbZ6TQ1o3x.'),
(15, 'Ahlem', './img/679101c925433-ahlem.png', 'boutayeb@outlook.fr', '$2y$10$lnJ6E2bcC0eWzOJCSgD9pu69shDRcqcl2eG4gRXg27za0E/U/IZBm'),
(16, 'Le\"V\"', './img/679111c99dbec-valentin.png', 'valentingillot@gmail.com', '$2y$10$qE36yktwpA3Rr9/TkiJA1eRvbvpN64lNNYbCPA3PaU5fM97FE/bOm'),
(17, 'thomas', './img/6791ec4394e87-thomas.png', 'thomas@gmail.com', '$2y$10$Tr5FeyRyMSh6b3h2RZ/yDOCgNHD0.07N5sR4A2XqEAjrpqjLsqrGu'),
(18, 'NeferNedjer', './img/679347e5984ab-vincent.png', 'nefer.nedjer@gmail.com', '$2y$10$QGbfD.j0h5lQR/9HA.3nuuW33w0dequom05PtHSpXoeLaNLIdoCdS'),
(19, 'CaveMan', './img/67937c0ea2c9a-full.png', 'caveMan@gmail.com', '$2y$10$FuAolTVFbwJGyD4i0QcizeWxcRji0bpgEZCkiFH.aCqMrsWgmZhPa'),
(20, 'Axll', './img/679762313b0c7-conception-tournesol-jaune-vif-pour-decorations_1308-130330.webp', 'axll.dbg@gmail.com', '$2y$10$BAONvnLPCbb.aoAezKvdx.jgw9xni7uvRg2UkcY6Gg.MuWMdld7QK'),
(21, 'Lara', './img/679764fdd30b1-e24e86e29f97dce02781f220c3ed9c27.jpg', 'lara@gmail.com', '$2y$10$HwfY8DWw1epsTnNU4zeUUedMRHx11H4OBizJ2/bjnimodJYiEctou');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
